# Generated by Django 3.1.3 on 2020-11-23 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesscripts', '0004_auto_20201123_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesscript',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 13, 2, 30, 462196)),
        ),
        migrations.AlterField(
            model_name='salesscript',
            name='scripttitle',
            field=models.TextField(),
        ),
    ]
