# Generated by Django 3.1.3 on 2020-11-25 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesscripts', '0007_auto_20201123_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesscript',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 10, 59, 4, 118990)),
        ),
    ]
